import {Injectable} from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Injectable()
export class SunbirdProfileDataSource
{
    dataUrl = "";
    sbHeaders : HttpHeaders;
    constructor(config, private _httpClient? : HttpClient )
    {
        this.sbHeaders = new HttpHeaders()
        .set('Accept', 'application/json')
        .set('Content-Type', 'application/json')
        .set('Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkMTc1MDIwNDdlODc0ODZjOTM0ZDQ1ODdlYTQ4MmM3MyJ9.7LWocwCn5rrCScFQYOne8_Op2EOo-xTCK5JCFarHKSs')
        .set('x-authenticated-user-token', 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ1WXhXdE4tZzRfMld5MG5PS1ZoaE5hU0gtM2lSSjdXU25ibFlwVVU0TFRrIn0.eyJqdGkiOiI2M2FjOTViMy04ZTVmLTQ0ZTMtOWUwOS1mMzA1NDRjOTcyYzEiLCJleHAiOjE1MTYwOTkzMTQsIm5iZiI6MCwiaWF0IjoxNTE2MDk1NzE0LCJpc3MiOiJodHRwczovL2Rldi5vcGVuLXN1bmJpcmQub3JnL2F1dGgvcmVhbG1zL3N1bmJpcmQiLCJhdWQiOiJhZG1pbi1jbGkiLCJzdWIiOiIyY2YwNTRiNS02MjI1LTQ5NTktODg5Zi1jMzYyOGE2MjAwMzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJjNzE5YWVhOS1jZmNmLTQzYmUtODFjMC1jODg2NDM4MDRmOTgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVzb3VyY2VfYWNjZXNzIjp7fSwibmFtZSI6Ik1hbmp1IERhdmFuYW0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYW5qdWRAaWxpbWkuaW4iLCJnaXZlbl9uYW1lIjoiTWFuanUiLCJmYW1pbHlfbmFtZSI6IkRhdmFuYW0iLCJlbWFpbCI6Im1hbmp1bmF0aGRAaWxpbWkuaW4ifQ.HpzhMDkqsKfIMTqa8p6wHwuLbVfZo50-Y5KRYPyE7Z4gJjSJSQ7YvQtYTUwv46lXWTM4zsSDe6zOeekrd1a7otBUNHT-XUz6viS5b3pos1SLjLfxlIseXmektPn9A7iGgK-Ia9L7wGb3HgFFiQBUb8pYzEKgFOnrC5rQz1ca-ftAUhfQFEwG8YfCcHbLdfu0q5gjkOhdCXZERGTQPBL2wWDekh_nyoqxnqpTLMM0ExQBNgFvR8DWFpbp2i62fZtaM1R8vH6PU1C9y18oNr3LUuRmX68U6tzoE1BxjyusANNRUWwrVSmQwIrYqWuwXoUnn9mePYwCr1qwGqLWUIOmqA');;
        // this.sbHeaders.append('Accept', 'application/json');
        // this.sbHeaders.append('Content-Type', 'application/json');
        // this.sbHeaders.append('Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkMTc1MDIwNDdlODc0ODZjOTM0ZDQ1ODdlYTQ4MmM3MyJ9.7LWocwCn5rrCScFQYOne8_Op2EOo-xTCK5JCFarHKSs');
        // this.sbHeaders.append('x-authenticated-user-token', 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ1WXhXdE4tZzRfMld5MG5PS1ZoaE5hU0gtM2lSSjdXU25ibFlwVVU0TFRrIn0.eyJqdGkiOiI2M2FjOTViMy04ZTVmLTQ0ZTMtOWUwOS1mMzA1NDRjOTcyYzEiLCJleHAiOjE1MTYwOTkzMTQsIm5iZiI6MCwiaWF0IjoxNTE2MDk1NzE0LCJpc3MiOiJodHRwczovL2Rldi5vcGVuLXN1bmJpcmQub3JnL2F1dGgvcmVhbG1zL3N1bmJpcmQiLCJhdWQiOiJhZG1pbi1jbGkiLCJzdWIiOiIyY2YwNTRiNS02MjI1LTQ5NTktODg5Zi1jMzYyOGE2MjAwMzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJjNzE5YWVhOS1jZmNmLTQzYmUtODFjMC1jODg2NDM4MDRmOTgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVzb3VyY2VfYWNjZXNzIjp7fSwibmFtZSI6Ik1hbmp1IERhdmFuYW0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYW5qdWRAaWxpbWkuaW4iLCJnaXZlbl9uYW1lIjoiTWFuanUiLCJmYW1pbHlfbmFtZSI6IkRhdmFuYW0iLCJlbWFpbCI6Im1hbmp1bmF0aGRAaWxpbWkuaW4ifQ.HpzhMDkqsKfIMTqa8p6wHwuLbVfZo50-Y5KRYPyE7Z4gJjSJSQ7YvQtYTUwv46lXWTM4zsSDe6zOeekrd1a7otBUNHT-XUz6viS5b3pos1SLjLfxlIseXmektPn9A7iGgK-Ia9L7wGb3HgFFiQBUb8pYzEKgFOnrC5rQz1ca-ftAUhfQFEwG8YfCcHbLdfu0q5gjkOhdCXZERGTQPBL2wWDekh_nyoqxnqpTLMM0ExQBNgFvR8DWFpbp2i62fZtaM1R8vH6PU1C9y18oNr3LUuRmX68U6tzoE1BxjyusANNRUWwrVSmQwIrYqWuwXoUnn9mePYwCr1qwGqLWUIOmqA');
        // {
        //     'Accept':'application/json',
        //     'Content-Type':'application/json',
        //     'Authorization':'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkMTc1MDIwNDdlODc0ODZjOTM0ZDQ1ODdlYTQ4MmM3MyJ9.7LWocwCn5rrCScFQYOne8_Op2EOo-xTCK5JCFarHKSs',
        //     'x-authenticated-user-token':'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ1WXhXdE4tZzRfMld5MG5PS1ZoaE5hU0gtM2lSSjdXU25ibFlwVVU0TFRrIn0.eyJqdGkiOiI2M2FjOTViMy04ZTVmLTQ0ZTMtOWUwOS1mMzA1NDRjOTcyYzEiLCJleHAiOjE1MTYwOTkzMTQsIm5iZiI6MCwiaWF0IjoxNTE2MDk1NzE0LCJpc3MiOiJodHRwczovL2Rldi5vcGVuLXN1bmJpcmQub3JnL2F1dGgvcmVhbG1zL3N1bmJpcmQiLCJhdWQiOiJhZG1pbi1jbGkiLCJzdWIiOiIyY2YwNTRiNS02MjI1LTQ5NTktODg5Zi1jMzYyOGE2MjAwMzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJjNzE5YWVhOS1jZmNmLTQzYmUtODFjMC1jODg2NDM4MDRmOTgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVzb3VyY2VfYWNjZXNzIjp7fSwibmFtZSI6Ik1hbmp1IERhdmFuYW0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYW5qdWRAaWxpbWkuaW4iLCJnaXZlbl9uYW1lIjoiTWFuanUiLCJmYW1pbHlfbmFtZSI6IkRhdmFuYW0iLCJlbWFpbCI6Im1hbmp1bmF0aGRAaWxpbWkuaW4ifQ.HpzhMDkqsKfIMTqa8p6wHwuLbVfZo50-Y5KRYPyE7Z4gJjSJSQ7YvQtYTUwv46lXWTM4zsSDe6zOeekrd1a7otBUNHT-XUz6viS5b3pos1SLjLfxlIseXmektPn9A7iGgK-Ia9L7wGb3HgFFiQBUb8pYzEKgFOnrC5rQz1ca-ftAUhfQFEwG8YfCcHbLdfu0q5gjkOhdCXZERGTQPBL2wWDekh_nyoqxnqpTLMM0ExQBNgFvR8DWFpbp2i62fZtaM1R8vH6PU1C9y18oNr3LUuRmX68U6tzoE1BxjyusANNRUWwrVSmQwIrYqWuwXoUnn9mePYwCr1qwGqLWUIOmqA'
        //     }
        this.dataUrl = config.baseUrl + config.endPoint;
        console.log("inside profile Data service ", config);
    }

    getData()
    {

        const headObj = new HttpHeaders()
        .set("Accept", "application/json")
        .set("Content-Type", "application/json")
        .append("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkMTc1MDIwNDdlODc0ODZjOTM0ZDQ1ODdlYTQ4MmM3MyJ9.7LWocwCn5rrCScFQYOne8_Op2EOo-xTCK5JCFarHKSs")
        .append("x-authenticated-user-token", "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ1WXhXdE4tZzRfMld5MG5PS1ZoaE5hU0gtM2lSSjdXU25ibFlwVVU0TFRrIn0.eyJqdGkiOiI2M2FjOTViMy04ZTVmLTQ0ZTMtOWUwOS1mMzA1NDRjOTcyYzEiLCJleHAiOjE1MTYwOTkzMTQsIm5iZiI6MCwiaWF0IjoxNTE2MDk1NzE0LCJpc3MiOiJodHRwczovL2Rldi5vcGVuLXN1bmJpcmQub3JnL2F1dGgvcmVhbG1zL3N1bmJpcmQiLCJhdWQiOiJhZG1pbi1jbGkiLCJzdWIiOiIyY2YwNTRiNS02MjI1LTQ5NTktODg5Zi1jMzYyOGE2MjAwMzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJjNzE5YWVhOS1jZmNmLTQzYmUtODFjMC1jODg2NDM4MDRmOTgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVzb3VyY2VfYWNjZXNzIjp7fSwibmFtZSI6Ik1hbmp1IERhdmFuYW0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYW5qdWRAaWxpbWkuaW4iLCJnaXZlbl9uYW1lIjoiTWFuanUiLCJmYW1pbHlfbmFtZSI6IkRhdmFuYW0iLCJlbWFpbCI6Im1hbmp1bmF0aGRAaWxpbWkuaW4ifQ.HpzhMDkqsKfIMTqa8p6wHwuLbVfZo50-Y5KRYPyE7Z4gJjSJSQ7YvQtYTUwv46lXWTM4zsSDe6zOeekrd1a7otBUNHT-XUz6viS5b3pos1SLjLfxlIseXmektPn9A7iGgK-Ia9L7wGb3HgFFiQBUb8pYzEKgFOnrC5rQz1ca-ftAUhfQFEwG8YfCcHbLdfu0q5gjkOhdCXZERGTQPBL2wWDekh_nyoqxnqpTLMM0ExQBNgFvR8DWFpbp2i62fZtaM1R8vH6PU1C9y18oNr3LUuRmX68U6tzoE1BxjyusANNRUWwrVSmQwIrYqWuwXoUnn9mePYwCr1qwGqLWUIOmqA");;

        return this._httpClient.get(this.dataUrl, { headers : headObj });
    }
}